
CREATE DATABASE Tickets
  DEFAULT CHARACTER SET Latin1
  DEFAULT COLLATE Latin1_Spanish_CI;

USE mysql;

-- CREATE USER 'ticket_dba'@'localhost' IDENTIFIED BY PASSWORD 'T1cketP0r+al';
CREATE USER 'ticket_dba'@'localhost' IDENTIFIED BY PASSWORD '*3D2E59C3C65B7456DC4E68E551201EDE90E14F05';

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, TRIGGER ON Tickets.* TO ticket_dba;

FLUSH PRIVILEGES; 

USE Tickets;




