
JAVA_HOME="/opt/jdk"
JDK_HOME="$JAVA_HOME"
JRE_HOME="$JAVA_HOME/jre"

TOMCAT_HOME="/opt/tomcat8"
CATALINA_HOME="$TOMCAT_HOME"

export JAVA_HOME JDK_HOME JRE_HOME TOMCAT_HOME CATALINA_HOME

PATH="$PATH:$JAVA_HOME/bin:$JRE_HOME/bin"
export PATH
