package hpd_incidentinterface_create_ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * HelpDesk_Submit_Service Create  
 *
 * This class was generated by Apache CXF 2.6.10
 * 2017-05-27T00:40:57.484-05:00
 * Generated source version: 2.6.10
 * 
 */
@WebServiceClient(name = "HPD_IncidentInterface_Create_WSService", 
                  wsdlLocation = "HPD_IncidentInterface_Create_WS.wsdl",
                  targetNamespace = "urn:HPD_IncidentInterface_Create_WS") 
public class HPDIncidentInterfaceCreateWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:HPD_IncidentInterface_Create_WS", "HPD_IncidentInterface_Create_WSService");
    public final static QName HPDIncidentInterfaceCreateWSPortTypeSoap = new QName("urn:HPD_IncidentInterface_Create_WS", "HPD_IncidentInterface_Create_WSPortTypeSoap");
    static {
        URL url = HPDIncidentInterfaceCreateWSService.class.getResource("HPD_IncidentInterface_Create_WS.wsdl");
        if (url == null) {
            url = HPDIncidentInterfaceCreateWSService.class.getClassLoader().getResource("HPD_IncidentInterface_Create_WS.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(HPDIncidentInterfaceCreateWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "HPD_IncidentInterface_Create_WS.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public HPDIncidentInterfaceCreateWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HPDIncidentInterfaceCreateWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HPDIncidentInterfaceCreateWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HPDIncidentInterfaceCreateWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HPDIncidentInterfaceCreateWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HPDIncidentInterfaceCreateWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HPDIncidentInterfaceCreateWSPortTypePortType
     */
    @WebEndpoint(name = "HPD_IncidentInterface_Create_WSPortTypeSoap")
    public HPDIncidentInterfaceCreateWSPortTypePortType getHPDIncidentInterfaceCreateWSPortTypeSoap() {
        return super.getPort(HPDIncidentInterfaceCreateWSPortTypeSoap, HPDIncidentInterfaceCreateWSPortTypePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HPDIncidentInterfaceCreateWSPortTypePortType
     */
    @WebEndpoint(name = "HPD_IncidentInterface_Create_WSPortTypeSoap")
    public HPDIncidentInterfaceCreateWSPortTypePortType getHPDIncidentInterfaceCreateWSPortTypeSoap(WebServiceFeature... features) {
        return super.getPort(HPDIncidentInterfaceCreateWSPortTypeSoap, HPDIncidentInterfaceCreateWSPortTypePortType.class, features);
    }

}
