package woi_workorderinterface_create_ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2017-05-27T00:41:19.357-05:00
 * Generated source version: 2.6.10
 *
 */

public class WOIWorkOrder_Server{

    protected WOIWorkOrder_Server() throws java.lang.Exception {

        System.out.println("Starting Server");
        // Object implementor = new WOIWorkOrdertInterfaceCreateWSPortTypePortTypeImpl();

        String address = "http://localhost:9012/WOI_WorkOrderInterface_Create_WS";
        Object implementor = new WorkOrderServer();
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new WOIWorkOrder_Server();
        System.out.println("Remedy Workorder Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
