package ctm_people_getinfo_ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2017-05-27T00:41:39.745-05:00
 * Generated source version: 2.6.10
 *
 */

public class CTMPeople_Server {

    protected CTMPeople_Server() throws Exception {

        System.out.println("Starting Server");
//      Object implementor = new CTMPeopleWSPortTypePortTypeImpl();
//        String address = "https://bcbeta100/arsys/services/ARService?server=BCBETA100&webService=CTM_People_GetInfo_WS";
        String address = "http://localhost:9008/CTM_People_GetInfo_WS";
        Object implementor = new PeopleInfoServer();
        Endpoint.publish( address, implementor );
    }

    public static void main(String args[]) throws java.lang.Exception {

        new CTMPeople_Server();
        System.out.println("CTMPeople Server ready...");
        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
