package ctm_people_getinfo_ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * CTM:People_GetInfo
 *
 * This class was generated by Apache CXF 2.6.10
 * 2017-05-27T00:41:39.761-05:00
 * Generated source version: 2.6.10
 * 
 */
@WebServiceClient(name = "CTM_People_GetInfo_WSService", 
                  wsdlLocation = "CTM_People_GetInfo_WS.wsdl",
                  targetNamespace = "urn:CTM_People_GetInfo_WS") 
public class CTMPeopleGetInfoWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:CTM_People_GetInfo_WS", "CTM_People_GetInfo_WSService");
    public final static QName CTMPeopleWSPortTypeSoap = new QName("urn:CTM_People_GetInfo_WS", "CTM_People_WSPortTypeSoap");
    static {
        URL url = CTMPeopleGetInfoWSService.class.getResource("CTM_People_GetInfo_WS.wsdl");
        if (url == null) {
            url = CTMPeopleGetInfoWSService.class.getClassLoader().getResource("CTM_People_GetInfo_WS.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(CTMPeopleGetInfoWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "CTM_People_GetInfo_WS.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CTMPeopleGetInfoWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CTMPeopleGetInfoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CTMPeopleGetInfoWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CTMPeopleGetInfoWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CTMPeopleGetInfoWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CTMPeopleGetInfoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CTMPeopleWSPortTypePortType
     */
    @WebEndpoint(name = "CTM_People_WSPortTypeSoap")
    public CTMPeopleWSPortTypePortType getCTMPeopleWSPortTypeSoap() {
        return super.getPort(CTMPeopleWSPortTypeSoap, CTMPeopleWSPortTypePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTMPeopleWSPortTypePortType
     */
    @WebEndpoint(name = "CTM_People_WSPortTypeSoap")
    public CTMPeopleWSPortTypePortType getCTMPeopleWSPortTypeSoap(WebServiceFeature... features) {
        return super.getPort(CTMPeopleWSPortTypeSoap, CTMPeopleWSPortTypePortType.class, features);
    }

}
