package ctm_people_getinfo_ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2017-05-27T00:41:39.667-05:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "urn:CTM_People_GetInfo_WS", name = "CTM_People_WSPortTypePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CTMPeopleWSPortTypePortType {

    @WebResult(name = "getListValues", targetNamespace = "urn:CTM_People_GetInfo_WS")
    @RequestWrapper(localName = "CTM_GetPeopleInfo", targetNamespace = "urn:CTM_People_GetInfo_WS", className = "ctm_people_getinfo_ws.InputMapping3")
    @WebMethod(operationName = "CTM_GetPeopleInfo", action = "urn:CTM_People_GetInfo_WS/CTM_GetPeopleInfo")
    @ResponseWrapper(localName = "CTM_GetPeopleInfoResponse", targetNamespace = "urn:CTM_People_GetInfo_WS", className = "ctm_people_getinfo_ws.OutputMapping3")
    public java.util.List<ctm_people_getinfo_ws.OutputMapping3.GetListValues> ctmGetPeopleInfo(
        @WebParam(name = "Qualification", targetNamespace = "urn:CTM_People_GetInfo_WS")
        java.lang.String qualification,
        @WebParam(name = "startRecord", targetNamespace = "urn:CTM_People_GetInfo_WS")
        java.lang.String startRecord,
        @WebParam(name = "maxLimit", targetNamespace = "urn:CTM_People_GetInfo_WS")
        java.lang.String maxLimit
    );
}
