package mx.com.gentera.people;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CTM_People_WSPortTypePortType", targetNamespace = "urn:CTM_People_GetInfo_WS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CTMPeopleWSPortTypePortType {


    /**
     * 
     * @param qualification
     * @param startRecord
     * @param maxLimit
     * @return
     *     returns java.util.List<mx.com.gentera.people.OutputMapping3.GetListValues>
     */
    @WebMethod(operationName = "CTM_GetPeopleInfo", action = "urn:CTM_People_GetInfo_WS/CTM_GetPeopleInfo")
    @WebResult(name = "getListValues", targetNamespace = "urn:CTM_People_GetInfo_WS")
    @RequestWrapper(localName = "CTM_GetPeopleInfo", targetNamespace = "urn:CTM_People_GetInfo_WS", className = "mx.com.gentera.people.InputMapping3")
    @ResponseWrapper(localName = "CTM_GetPeopleInfoResponse", targetNamespace = "urn:CTM_People_GetInfo_WS", className = "mx.com.gentera.people.OutputMapping3")
    public List<mx.com.gentera.people.OutputMapping3 .GetListValues> ctmGetPeopleInfo(
        @WebParam(name = "Qualification", targetNamespace = "urn:CTM_People_GetInfo_WS")
        String qualification,
        @WebParam(name = "startRecord", targetNamespace = "urn:CTM_People_GetInfo_WS")
        String startRecord,
        @WebParam(name = "maxLimit", targetNamespace = "urn:CTM_People_GetInfo_WS")
        String maxLimit);

}
