package mx.com.gentera.people;

// import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
// import javax.xml.ws.WebServiceException;
// import javax.xml.ws.WebServiceFeature;


/**
 * CTM:People_GetInfo
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CTM_People_GetInfo_WSService", targetNamespace = "urn:CTM_People_GetInfo_WS", wsdlLocation = "file:/public/tickets/CTM_People_GetInfo_WS.wsdl")
public class CTMPeopleGetInfoWSService extends Service
{
/*    
    private final static URL CTMPEOPLEGETINFOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CTMPEOPLEGETINFOWSSERVICE_EXCEPTION;
*/    
    private final static QName CTMPEOPLEGETINFOWSSERVICE_QNAME = new QName("urn:CTM_People_GetInfo_WS", "CTM_People_GetInfo_WSService");

/*   
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/public/tickets/CTM_People_GetInfo_WS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CTMPEOPLEGETINFOWSSERVICE_WSDL_LOCATION = url;
        CTMPEOPLEGETINFOWSSERVICE_EXCEPTION = e;
    }

    public CTMPeopleGetInfoWSService() {
        super(__getWsdlLocation(), CTMPEOPLEGETINFOWSSERVICE_QNAME);
    }

    public CTMPeopleGetInfoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CTMPEOPLEGETINFOWSSERVICE_QNAME, features);
    }
*/
    public CTMPeopleGetInfoWSService(URL wsdlLocation) {
        
      super( wsdlLocation, CTMPEOPLEGETINFOWSSERVICE_QNAME );
    }

    public CTMPeopleGetInfoWSService( String wsdlLocation ) throws Exception {
        
      super( new URL( wsdlLocation ), CTMPEOPLEGETINFOWSSERVICE_QNAME );
    }
    
/*    
    public CTMPeopleGetInfoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CTMPEOPLEGETINFOWSSERVICE_QNAME, features);
    }

    public CTMPeopleGetInfoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CTMPeopleGetInfoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
*/
    /**
     * 
     * @return
     *     returns CTMPeopleWSPortTypePortType
     */
    @WebEndpoint(name = "CTM_People_WSPortTypeSoap")
    public CTMPeopleWSPortTypePortType getCTMPeopleWSPortTypeSoap() {
        
      return super.getPort(new QName("urn:CTM_People_GetInfo_WS", "CTM_People_WSPortTypeSoap"), CTMPeopleWSPortTypePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTMPeopleWSPortTypePortType
     */
/*    
    @WebEndpoint(name = "CTM_People_WSPortTypeSoap")
    public CTMPeopleWSPortTypePortType getCTMPeopleWSPortTypeSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn:CTM_People_GetInfo_WS", "CTM_People_WSPortTypeSoap"), CTMPeopleWSPortTypePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CTMPEOPLEGETINFOWSSERVICE_EXCEPTION!= null) {
            throw CTMPEOPLEGETINFOWSSERVICE_EXCEPTION;
        }
        return CTMPEOPLEGETINFOWSSERVICE_WSDL_LOCATION;
    }
*/
}
